name: Build dev

on:
  push:
    branches:
      - '!master'
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Setup PHP with Xdebug
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3'
        extensions: curl
        coverage: pcov

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      
    - name: Fix style
      uses: docker://oskarstark/php-cs-fixer-ga
      with:
        args: --config=.php_cs.php --allow-risky=yes
  
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v2.3.0
      with:
        commit_message: Fix styling
        branch: ${{ steps.extract_branch.outputs.branch }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        
#     Seems it doesn't work ))
#    - name: analyze code with StyleCI
#      uses: ghostwriter/styleci-action@latest
#      with:
#        styleci_api_key: ${{ secrets.STYLECI_API_KEY }}
        
    - name: Run tests with phpunit/phpunit
      run: vendor/bin/phpunit --coverage-clover=coverage.xml
    
    - name: Send code coverage report to Codecov.io
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
      
